-- CICLO 1
DELETE FROM MATERIASPORESTUDIANTE;
DELETE FROM PROGRAMASPORESTUDIANTES;
DELETE FROM PREINSCRIPCIONES;
DELETE FROM PREREQUISITOSMATERIAS;
DELETE FROM NOTAS;
DELETE FROM GRUPOS;
DELETE FROM MATERIAS;
DELETE FROM AREAS;
DELETE FROM CENTROSDEESTUDIOS;
DELETE FROM NUCLEOSDEFORMACION;
DELETE FROM ESTUDIANTES;
DELETE FROM PROFESORES;
DELETE FROM DIRECTORES;
DELETE FROM DEPARTAMENTOS;
DELETE FROM PROGRAMASACADEMICOS;

-- CICLO 2

DELETE FROM CANCELACIONES;
DELETE FROM NOTIFICACIONES;