-- CICLO 1

ALTER TABLE  MATERIASPORESTUDIANTE
    ADD CONSTRAINT FK_MATERIASPORESTUDIANTES_ESTUDIANTES FOREIGN KEY (idEstudiante)
        REFERENCES ESTUDIANTES (idUsuario);

ALTER TABLE DEPARTAMENTOS
    ADD CONSTRAINT FK_DEPARTAMENTOS_DIRECTORES FOREIGN KEY (idDirector)
        REFERENCES DIRECTORES (idUsuario);

ALTER TABLE GRUPOS
    ADD CONSTRAINT FK_GRUPOS_PROFESORES FOREIGN KEY (idProfesor)
        REFERENCES PROFESORES (idUsuario);

ALTER TABLE PREINSCRIPCIONES
    ADD CONSTRAINT FK_PREINSCRIPCIONES_ESTUDIANTES FOREIGN KEY (idEstudiante)
        REFERENCES ESTUDIANTES (idUsuario);

ALTER TABLE AREAS
    ADD CONSTRAINT FK_AREAS_DEPARTAMENTOS FOREIGN KEY (idDepartamento)
        REFERENCES DEPARTAMENTOS (idDepartamento);

ALTER TABLE AREAS
    ADD CONSTRAINT FK_AREAS_DIRECTORES FOREIGN KEY (idDirector)
        REFERENCES DIRECTORES (idUsuario);

ALTER TABLE MATERIAS
    ADD CONSTRAINT FK_MATERIAS_AREAS FOREIGN KEY (idArea)
        REFERENCES AREAS (idArea);

ALTER TABLE MATERIAS
    ADD CONSTRAINT FK_MATERIAS_CENTROSDEESTUDIOS FOREIGN KEY (idCentroDeEstudios)
        REFERENCES CENTROSDEESTUDIOS (idCentroEstudios);

ALTER TABLE MATERIAS
    ADD CONSTRAINT FK_MATERIAS_NUCLEOSDEFORMACION FOREIGN KEY (idNucleoDeFormacion)
        REFERENCES NUCLEOSDEFORMACION (idNucleoFormacion);

ALTER TABLE CENTROSDEESTUDIOS
    ADD CONSTRAINT FK_CENTROSDEESTUDIOS_DIRECTORES FOREIGN KEY (idDirector)
        REFERENCES DIRECTORES (idUsuario);

ALTER TABLE CENTROSDEESTUDIOS
    ADD CONSTRAINT FK_CENTROSDEESTUDIOS_PROGRAMASACADEMICOS FOREIGN KEY (idProgramaAcademico)
        REFERENCES PROGRAMASACADEMICOS (idPrograma);

ALTER TABLE NOTAS
    ADD CONSTRAINT FK_NOTAS_ESTUDIANTES FOREIGN KEY (idEstudiante)
        REFERENCES ESTUDIANTES (idUsuario);

ALTER TABLE PROGRAMASPORESTUDIANTES
    ADD CONSTRAINT FK_PROGRAMASPORESTUDIANTES_PROGRAMASACADEMICOS FOREIGN KEY (idPrograma)
        REFERENCES PROGRAMASACADEMICOS (idPrograma);

ALTER TABLE PROGRAMASPORESTUDIANTES
    ADD CONSTRAINT FK_PROGRAMASPORESTUDIANTES_ESTUDIANTE FOREIGN KEY (idEstudiante)
        REFERENCES ESTUDIANTES (idUsuario);

ALTER TABLE  MATERIASPORESTUDIANTE
    ADD CONSTRAINT FK_MATERIASPORESTUDIANTES_MATERIAS FOREIGN KEY (idMateria)
        REFERENCES MATERIAS (idMateria);

ALTER TABLE NOTAS
    ADD CONSTRAINT FK_NOTAS_MATERIAS FOREIGN KEY (idMateria)
        REFERENCES MATERIAS (idMateria);

ALTER TABLE PREREQUISITOSMATERIAS
    ADD CONSTRAINT FK_PREREQUISITOSMATERIAS_MATERIAS FOREIGN KEY (idMateria)
        REFERENCES MATERIAS (idMateria);

ALTER TABLE PREREQUISITOSMATERIAS
    ADD CONSTRAINT FK_PREREQUISITOSMATERIAS_MATERIASREQUIRIDA FOREIGN KEY (idMateriaRequisito)
        REFERENCES MATERIAS (idMateria);

ALTER TABLE PREINSCRIPCIONES
    ADD CONSTRAINT FK_PREINSCRIPCIONES_MATERIAS FOREIGN KEY (idMateria)
        REFERENCES MATERIAS (idMateria);

ALTER TABLE GRUPOS
    ADD CONSTRAINT FK_GRUPOS_MATERIAS FOREIGN KEY (idMateria)
        REFERENCES MATERIAS (idMateria);

ALTER TABLE TITULOS
    ADD CONSTRAINT FK_TITULOS_PROFESORES FOREIGN KEY (idProfesor)
        REFERENCES PROFESORES (idUsuario);

-- CICLO 2

ALTER TABLE CANCELACIONES
    ADD CONSTRAINT FK_CANCELACION_ESESTUDIANTES FOREIGN KEY (IDESTUDIANTE)
        REFERENCES ESTUDIANTES (IDUSUARIO);

ALTER TABLE CANCELACIONES
    ADD CONSTRAINT FK_CANCELACIONES_NOTIFICACIONES FOREIGN KEY (idNotificacion)
        REFERENCES NOTIFICACIONES (idNotificacion);

ALTER TABLE CANCELACIONES
    ADD CONSTRAINT FK_CANCELACIONES_MATERIAS FOREIGN KEY (idMateria)
        REFERENCES MATERIAS (idMateria);