-- CICLO 1

DROP TABLE DIRECTORES CASCADE CONSTRAINTS;
DROP TABLE PROFESORES CASCADE CONSTRAINTS;
DROP TABLE ESTUDIANTES CASCADE CONSTRAINTS;
DROP TABLE MATERIASPORESTUDIANTE CASCADE CONSTRAINTS;
DROP TABLE DEPARTAMENTOS CASCADE CONSTRAINTS;
DROP TABLE GRUPOS CASCADE CONSTRAINTS;
DROP TABLE PREINSCRIPCIONES CASCADE CONSTRAINTS;
DROP TABLE AREAS CASCADE CONSTRAINTS;
DROP TABLE MATERIAS CASCADE CONSTRAINTS;
DROP TABLE PREREQUISITOSMATERIAS CASCADE CONSTRAINTS;
DROP TABLE CENTROSDEESTUDIOS CASCADE CONSTRAINTS;
DROP TABLE NUCLEOSDEFORMACION CASCADE CONSTRAINTS;
DROP TABLE NOTAS CASCADE CONSTRAINTS;
DROP TABLE PROGRAMASACADEMICOS CASCADE CONSTRAINTS;
DROP TABLE PROGRAMASPORESTUDIANTES CASCADE CONSTRAINTS;
DROP TABLE TITULOS CASCADE CONSTRAINTS;

-- CICLO 2

DROP TABLE CANCELACIONES CASCADE CONSTRAINTS;
DROP TABLE NOTIFICACIONES CASCADE CONSTRAINTS;