-- CICLO 1

-- GRUPOS → PROFESORES
ALTER TABLE GRUPOS
    ADD CONSTRAINT fk_grupos_profesor
        FOREIGN KEY (idProfesor)
            REFERENCES PROFESORES(idUsuario) ON DELETE SET NULL;

-- AREAS → DEPARTAMENTOS
ALTER TABLE AREAS
    ADD CONSTRAINT fk_areas_departamento FOREIGN KEY (idDepartamento)
        REFERENCES DEPARTAMENTOS(idDepartamento)
            ON DELETE CASCADE;

-- AREAS → DIRECTORES
ALTER TABLE AREAS
    ADD CONSTRAINT fk_areas_director FOREIGN KEY (idDirector)
        REFERENCES DIRECTORES(idUsuario)
            ON DELETE SET NULL;

-- MATERIAS → AREAS
ALTER TABLE MATERIAS
    ADD CONSTRAINT fk_materias_area FOREIGN KEY (idArea)
        REFERENCES AREAS(idArea)
            ON DELETE CASCADE;

-- MATERIAS → CENTROSDEESTUDIOS
ALTER TABLE MATERIAS
    ADD CONSTRAINT fk_materias_centro FOREIGN KEY (idCentroDeEstudios)
        REFERENCES CENTROSDEESTUDIOS(idCentroEstudios)
            ON DELETE SET NULL;

-- MATERIAS → NUCLEOSDEFORMACION
ALTER TABLE MATERIAS
    ADD CONSTRAINT fk_materias_nucleo FOREIGN KEY (idNucleoDeFormacion)
        REFERENCES NUCLEOSDEFORMACION(idNucleoFormacion)
            ON DELETE SET NULL;

-- NOTAS → ESTUDIANTES
ALTER TABLE NOTAS
    ADD CONSTRAINT fk_notas_estudiante FOREIGN KEY (idEstudiante)
        REFERENCES ESTUDIANTES(idUsuario)
            ON DELETE CASCADE;

-- PROGRAMASPORESTUDIANTES → ESTUDIANTES
ALTER TABLE PROGRAMASPORESTUDIANTES
    ADD CONSTRAINT fk_prog_estudiante FOREIGN KEY (idEstudiante)
        REFERENCES ESTUDIANTES(idUsuario)
            ON DELETE CASCADE;

-- PROGRAMASPORESTUDIANTES → PROGRAMASACADEMICOS
ALTER TABLE PROGRAMASPORESTUDIANTES
    ADD CONSTRAINT fk_prog_programa FOREIGN KEY (idPrograma)
        REFERENCES PROGRAMASACADEMICOS(idPrograma)
            ON DELETE SET NULL;

-- MATERIASPORESTUDIANTE → ESTUDIANTES
ALTER TABLE MATERIASPORESTUDIANTE
    ADD CONSTRAINT fk_matpores_est FOREIGN KEY (idEstudiante)
        REFERENCES ESTUDIANTES(idUsuario)
            ON DELETE CASCADE;

-- PREINSCRIPCIONES → ESTUDIANTES
ALTER TABLE PREINSCRIPCIONES
    ADD CONSTRAINT fk_preins_est FOREIGN KEY (idEstudiante)
        REFERENCES ESTUDIANTES(idUsuario)
            ON DELETE CASCADE;

-- PREINSCRIPCIONES → MATERIAS
ALTER TABLE PREINSCRIPCIONES
    ADD CONSTRAINT fk_preins_materia FOREIGN KEY (idMateria)
        REFERENCES MATERIAS(idMateria)
            ON DELETE CASCADE;

-- MATERIASPORESTUDIANTE → MATERIAS
ALTER TABLE MATERIASPORESTUDIANTE
    ADD CONSTRAINT fk_matpores_mat FOREIGN KEY (idMateria)
        REFERENCES MATERIAS(idMateria)
            ON DELETE CASCADE;

-- PREREQUISITOSMATERIAS
ALTER TABLE PREREQUISITOSMATERIAS
    ADD CONSTRAINT fk_prereq_materia FOREIGN KEY (idMateria)
        REFERENCES MATERIAS(idMateria)
            ON DELETE CASCADE;

-- PREREQUISITOSMATERIAS → MATERIAS
ALTER TABLE PREREQUISITOSMATERIAS
    ADD CONSTRAINT fk_prereq_requisito FOREIGN KEY (idMateriaRequisito)
        REFERENCES MATERIAS(idMateria)
            ON DELETE CASCADE;

-- NOTAS → MATERIAS
ALTER TABLE NOTAS
    ADD CONSTRAINT fk_notas_materia FOREIGN KEY (idMateria)
        REFERENCES MATERIAS(idMateria)
            ON DELETE CASCADE;

-- GRUPOS → MATERIAS
ALTER TABLE GRUPOS
    ADD CONSTRAINT fk_grupos_materia FOREIGN KEY (idMateria)
        REFERENCES MATERIAS(idMateria)
            ON DELETE CASCADE;

-- DEPARTAMENTOS → DIRECTORES
ALTER TABLE DEPARTAMENTOS
    ADD CONSTRAINT fk_depart_director FOREIGN KEY (idDirector)
        REFERENCES DIRECTORES(idUsuario)
            ON DELETE SET NULL;

-- CENTROSDEESTUDIOS → DIRECTORES
ALTER TABLE CENTROSDEESTUDIOS
    ADD CONSTRAINT fk_centro_director FOREIGN KEY (idDirector)
        REFERENCES DIRECTORES(idUsuario)
            ON DELETE SET NULL;

-- CENTROSDEESTUDIOS → PROGRAMASACADEMICOS
ALTER TABLE CENTROSDEESTUDIOS
    ADD CONSTRAINT fk_centro_programa FOREIGN KEY (idProgramaAcademico)
        REFERENCES PROGRAMASACADEMICOS(idPrograma)
            ON DELETE CASCADE;

-- TITULOS → PROFESORES
ALTER TABLE TITULOS
    ADD CONSTRAINT fk_titulos_profesor FOREIGN KEY (idProfesor)
        REFERENCES PROFESORES(idUsuario)
            ON DELETE CASCADE;

--CICLO 2

-- CANCELACIONES → ESTUDIANTES
ALTER TABLE CANCELACIONES
    ADD CONSTRAINT fk_cancel_est FOREIGN KEY (idEstudiante)
        REFERENCES ESTUDIANTES(idUsuario)
            ON DELETE CASCADE;

-- CANCELACIONES → NOTIFICACIONES
ALTER TABLE CANCELACIONES
    ADD CONSTRAINT fk_cancel_notif FOREIGN KEY (idNotificacion)
        REFERENCES NOTIFICACIONES(idNotificacion)
            ON DELETE CASCADE;

-- CANCELACIONES → MATERIAS
ALTER TABLE CANCELACIONES
    ADD CONSTRAINT fk_cancel_materia FOREIGN KEY (idMateria)
        REFERENCES MATERIAS(idMateria)
            ON DELETE CASCADE;