-- CICLO 1

-- MATERIASPORESTUDIANTE
ALTER TABLE MATERIASPORESTUDIANTE DROP CONSTRAINT FK_MATERIASPORESTUDIANTES_ESTUDIANTES;
ALTER TABLE MATERIASPORESTUDIANTE DROP CONSTRAINT FK_MATERIASPORESTUDIANTES_MATERIAS;

-- DEPARTAMENTOS
ALTER TABLE DEPARTAMENTOS DROP CONSTRAINT FK_DEPARTAMENTOS_DIRECTORES;

-- GRUPOS
ALTER TABLE GRUPOS DROP CONSTRAINT FK_GRUPOS_PROFESORES;
ALTER TABLE GRUPOS DROP CONSTRAINT FK_GRUPOS_MATERIAS;

-- PREINSCRIPCIONES
ALTER TABLE PREINSCRIPCIONES DROP CONSTRAINT FK_PREINSCRIPCIONES_ESTUDIANTES;
ALTER TABLE PREINSCRIPCIONES DROP CONSTRAINT FK_PREINSCRIPCIONES_MATERIAS;

-- AREAS
ALTER TABLE AREAS DROP CONSTRAINT FK_AREAS_DEPARTAMENTOS;
ALTER TABLE AREAS DROP CONSTRAINT FK_AREAS_DIRECTORES;

-- MATERIAS
ALTER TABLE MATERIAS DROP CONSTRAINT FK_MATERIAS_AREAS;
ALTER TABLE MATERIAS DROP CONSTRAINT FK_MATERIAS_CENTROSDEESTUDIOS;
ALTER TABLE MATERIAS DROP CONSTRAINT FK_MATERIAS_NUCLEOSDEFORMACION;
ALTER TABLE MATERIAS DROP CONSTRAINT FK_MATERIAS_ESTUDIANTES;

-- CENTROSDEESTUDIOS
ALTER TABLE CENTROSDEESTUDIOS DROP CONSTRAINT FK_CENTROSDEESTUDIOS_DIRECTORES;
ALTER TABLE CENTROSDEESTUDIOS DROP CONSTRAINT FK_CENTROSDEESTUDIOS_PROGRAMASACADEMICOS;

-- NOTAS
ALTER TABLE NOTAS DROP CONSTRAINT FK_NOTAS_ESTUDIANTES;
ALTER TABLE NOTAS DROP CONSTRAINT FK_NOTAS_MATERIAS;

-- PROGRAMASPORESTUDIANTES
ALTER TABLE PROGRAMASPORESTUDIANTES DROP CONSTRAINT FK_PROGRAMASPORESTUDIANTES_PROGRAMASACADEMICOS;
ALTER TABLE PROGRAMASPORESTUDIANTES DROP CONSTRAINT FK_PROGRAMASPORESTUDIANTES_ESTUDIANTE;

-- PREREQUISITOSMATERIAS
ALTER TABLE PREREQUISITOSMATERIAS DROP CONSTRAINT FK_PREREQUISITOSMATERIAS_MATERIAS;
ALTER TABLE PREREQUISITOSMATERIAS DROP CONSTRAINT FK_PREREQUISITOSMATERIAS_MATERIASREQUIRIDA;

-- TITULOS
ALTER TABLE TITULOS DROP CONSTRAINT FK_TITULOS_PROFESORES;

-- CICLO 2

-- CANCELACIONES
ALTER TABLE CANCELACIONES DROP CONSTRAINT FK_CANCELACION_ESESTUDIANTES;
ALTER TABLE CANCELACIONES DROP CONSTRAINT FK_CANCELACIONES_NOTIFICACIONES;
ALTER TABLE CANCELACIONES DROP CONSTRAINT FK_CANCELACIONES_MATERIAS;