-- CICLO 1

ALTER TABLE MATERIAS DROP CONSTRAINT ck_suma_horas_materias;
ALTER TABLE DIRECTORES DROP CONSTRAINT ck_fecha_nombramiento;
ALTER TABLE ESTUDIANTES DROP CONSTRAINT ck_fecha_ingreso;
ALTER TABLE PROFESORES DROP CONSTRAINT ck_experiencia_tipo_contrato;
ALTER TABLE MATERIAS DROP CONSTRAINT ck_nivel_creditos;
ALTER TABLE GRUPOS DROP CONSTRAINT ck_cupo_duracion;
ALTER TABLE PREREQUISITOSMATERIAS DROP CONSTRAINT ck_no_auto_requisito;
ALTER TABLE MATERIAS DROP CONSTRAINT ck_creditos_horas_totales;
ALTER TABLE MATERIAS DROP CONSTRAINT ck_modalidad_horas;
ALTER TABLE DIRECTORES DROP CONSTRAINT ck_presupuesto_nivel;

-- CICLO 2

ALTER TABLE CANCELACIONES DROP CONSTRAINT ck_asesoria_motivo;
