-- Definición de roles
CREATE ROLE DIRECTOR;
CREATE ROLE PROFESOR;
CREATE ROLE ESTUDIANTE;
CREATE ROLE VICERRECTORIA_ACADEMICA;

-- Asignación de permisos para 'DIRECTOR'
GRANT EXECUTE ON PKG_DIRECTOR TO DIRECTOR;

-- Asignación de permisos para 'PROFESOR'
GRANT EXECUTE ON PKG_PROFESOR TO PROFESOR;

-- Asignación de permisos para 'ESTUDIANTE'
GRANT EXECUTE ON PKG_ESTUDIANTE TO ESTUDIANTE;

-- Asignación de permisos para 'VICERRECTORIA_ACADEMICA'
GRANT EXECUTE ON PKG_VICERRECTORIA TO VICERRECTORIA_ACADEMICA;

