-- Eliminación de paquetes

DROP PACKAGE PKG_ESTUDIANTE;
DROP PACKAGE PKG_PROFESOR;
DROP PACKAGE PKG_DIRECTOR;
DROP PACKAGE PKG_VICERRECTORIA;

-- Eliminación de roles

DROP ROLE DIRECTOR;
DROP ROLE PROFESOR;
DROP ROLE ESTUDIANTE;
DROP ROLE VICERRECTORIA_ACADEMICA;